//
//  Graph.swift
//  Adjacency Table
//
//  Created by Dylan Conklin on 7/21/23.
//

import Foundation
import SwiftData

typealias Vertex = String

enum GraphType {
    case mst
    case given
}

@Model
class Graph: Equatable {
    private var graphEdges: Set<Edge>
    private var graphVertices: Set<Vertex>
    var name: String?
    var lastAccessed: Date
    var edgeStyles: [UUID: EdgeStyle]
    var id: UUID

    init(graphEdges: Set<Edge> = Set<Edge>(),
         graphVertices: Set<Vertex> = Set<Vertex>(),
         name: String? = nil,
         edgeStyles: [UUID: EdgeStyle] = [UUID: EdgeStyle]()) {
        self.graphEdges = graphEdges
        self.graphVertices = graphVertices
        self.name = name
        self.lastAccessed = Date.now
        self.edgeStyles = edgeStyles
        self.id = UUID()
    }

    static func == (lhs: Graph, rhs: Graph) -> Bool {
        return lhs.edges == rhs.edges && lhs.vertices == rhs.vertices
    }

    func insert(_ vertex: Vertex) {
        graphVertices.insert(vertex)
    }

    func insert(_ edge: Edge, withStyle style: EdgeStyle? = nil) {
        graphEdges.insert(edge)
        insert(edge.from)
        insert(edge.to)
        edgeStyles[edge.id] = style
    }

    func remove(_ vertex: Vertex) {
        graphEdges.filter({ $0.vertices.contains(vertex) }).forEach { edge in
            remove(edge)
        }
        graphVertices.remove(vertex)
    }

    func remove(_ vertices: any Collection<Vertex>) {
        vertices.forEach { vertex in
            remove(vertex)
        }
    }

    func remove(_ edge: Edge) {
        graphEdges.remove(edge)
    }

    func remove(_ edges: any Collection<Edge>) {
        edges.forEach { edge in
            remove(edge)
        }
    }

    /// Returns the vertices of the graph
    var vertices: [Vertex] {
        get {
            graphVertices.sorted()
        }
        set {
            let newVertices = Set<Vertex>(newValue)
            let difference = Set<Vertex>(vertices).symmetricDifference(newVertices)

            if vertices.count < newVertices.count {
                graphVertices.formUnion(difference)
            } else {
                difference.forEach { remove($0) }
            }
        }
    }

    /// Calculates the total cost of the graph
    /// The cost is the sum of the weight (length) of all the edges in the graph
    var cost: Double {
        edges.reduce(0.0, { $0 + $1.weight })
    }

    /// Generate the Minimum Spanning Tree (MST)
    /// - Returns: The MST Graph generated by the edges in the graph
    var mst: Graph {
        if !isTree {
            return Graph()
        }

        let graph: Graph = self.copy
        var verticesLeft: Set<Vertex> = Set<Vertex>(graph.vertices) // vertices that don't have an edge
        let MST: Graph = Graph()

        while let edge = graph.edges.sorted(by: { $0.weight < $1.weight }).first(where: {
            let groupA = Set<Vertex>($0.vertices).intersection(verticesLeft)
            let groupB = Set<Vertex>($0.vertices).intersection(MST.vertices)
            return !groupA.isEmpty && !groupB.isEmpty
        }) ?? (MST.isEmpty ? graph.edges.sorted(by: { $0.weight < $1.weight }).first : nil) {
            MST.insert(edge)
            graph.remove(edge)
            verticesLeft.subtract(edge.vertices)
        }

        return MST
    }

    /// Returns edges of the graph, in the form of Edge objects in an array
    var edges: [Edge] {
        get {
            graphEdges.sorted(by: {
                if $0.from != $1.from {
                    return $0.from < $1.from
                } else if $0.to != $1.to {
                    return $0.to < $1.to
                } else {
                    return $0.weight < $1.weight
                }
            })
        }
        set {
            let difference = Set(newValue).symmetricDifference(Set(edges))
            let addOrRemove = edges.count < newValue.count ? { (edge: Edge) in
                self.insert(edge)
            } : { (edge: Edge) in
                self.remove(edge)
            }
            difference.forEach(addOrRemove)
        }
    }

    func edges(from: Vertex, to: Vertex, directional: Bool = true) -> Set<Edge> {
        return Set<Edge>(edges.filter { edge in
            directional ? (edge.to == to && edge.from == from) : (Set<Vertex>(edge.vertices) == Set<Vertex>([from, to]))
        })
    }

    func edges(connectedTo vertex: Vertex) -> Set<Edge> {
        return Set(edges.filter { $0.vertices.contains(vertex) })
    }

    func edges(connectedTo vertices: any Collection<Vertex>) -> Set<Edge> {
        return vertices.reduce(into: Set<Edge>()) { result, vertex in
            result.formUnion(self.edges(connectedTo: vertex))
        }
    }

    var leaves: Set<Vertex> {
        Set<Vertex>(vertices.filter { vertex in
            graphEdges.filter { $0.from == vertex }.isEmpty
        })
    }

    var loops: Set<Edge> {
        Set(edges.filter { $0.from == $0.to })
    }

    func deleteEdges() {
        graphEdges = Set<Edge>()
    }

    func deleteEdgesAndVertices() {
        deleteEdges()
        graphVertices = Set<Vertex>()
    }

    func deleteLeaves() {
        remove(leaves)
    }

    func deleteDetachedVertices() {
        vertices.filter { edges(connectedTo: $0).isEmpty }.forEach { remove($0) }
    }

    var copy: Graph {
        Graph(graphEdges: self.graphEdges, graphVertices: self.graphVertices)
    }
}
